In [3]:
import torch

x = torch.arange(12, dtype = torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
len(x), x.shape, x.size()

(12, torch.Size([12]), torch.Size([12]))

In [5]:
x.reshape(3, 4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [6]:
torch.zeros(size = (2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones(size = (2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
torch.randn(size = (3, 4))

tensor([[-0.4369, -0.4364, -0.7454,  0.0066],
        [ 0.9051, -0.9902,  2.4707,  1.7459],
        [ 0.7774,  0.7316,  0.4069, -1.7111]])

Create tensor from nested lists

In [9]:
torch.tensor(data = [[2, 1, 3, 2], [1, 4, 5, 6]])

tensor([[2, 1, 3, 2],
        [1, 4, 5, 6]])

Slicing

In [10]:
x, x[-1], x[1:4]

(tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 tensor(11.),
 tensor([1., 2., 3.]))

#### 3. Operations

In [11]:
torch.exp(x)

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04])

Concatenate multiple tensors:

In [12]:
x = torch.arange(12).reshape(3, 4)
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

print("x = \n", x)
print("y = \n", y)
print("concat axis = 0 \n", torch.cat((x, y), dim = 0))
print("concat axis = 1 \n", torch.cat((x, y), dim = 1))

x = 
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
y = 
 tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])
concat axis = 0 
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
concat axis = 1 
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


In [13]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [14]:
x.sum(), torch.sum(x)

(tensor(66), tensor(66))

In [15]:
z = torch.zeros_like(y)
print("id(z) = ", id(z))
z[:] = x + y
print("id(z) = ", id(z))
z += x
print("id(z) = ", id(z))

id(z) =  1842413505808
id(z) =  1842413505808
id(z) =  1842413505808


Convert to other Python objects

In [16]:
a = x.numpy()
b = torch.from_numpy(a)
type(a), type(b)

(numpy.ndarray, torch.Tensor)

In [17]:
import torch
# Kiểm tra xem PyTorch có nhận diện GPU không
print("CUDA available:", torch.cuda.is_available())

# Kiểm tra số lượng GPU
print("Number of GPUs:", torch.cuda.device_count())

# Kiểm tra tên GPU (nếu có)
if torch.cuda.is_available():
    print("GPU Name:", torch.cuda.get_device_name(0))

# Kiểm tra GPU hiện đang được sử dụng
# print("Current GPU:", torch.cuda.current_device())


CUDA available: True
Number of GPUs: 1
GPU Name: NVIDIA GeForce GTX 1650 with Max-Q Design
