In [24]:
import torch

In [25]:
y = torch.tensor(3.0)
x = torch.tensor(2.0)

x + y, x - y, x / y, x ** y

(tensor(5.), tensor(-1.), tensor(0.6667), tensor(8.))

In [26]:
A = torch.randn(size = (1, 3))
A, A.T

(tensor([[ 0.4664, -0.1000, -0.2839]]),
 tensor([[ 0.4664],
         [-0.1000],
         [-0.2839]]))

In [27]:
A = torch.arange(12).reshape(3, 4)
B = A.clone()

A * B

tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]])

#### Vector product (dot)

In [28]:
y = torch.ones(3, dtype = torch.float32)
x = (y.clone()).T
x, y, torch.dot(x, y)

(tensor([1., 1., 1.]), tensor([1., 1., 1.]), tensor(3.))

In [29]:
y = y.reshape(len(y), 1)
x = y.reshape(1, len(y))
torch.mm(y, x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

#### Matrix product

In [30]:
a = torch.arange(12).reshape(3, 4)
b = torch.arange(12).reshape(4, 3)

torch.mm(a, b)

tensor([[ 42,  48,  54],
        [114, 136, 158],
        [186, 224, 262]])

#### Norm

In [31]:
u = y.clone()
torch.norm(u)

tensor(1.7321)