In [1]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [2]:
x.requires_grad_(True)
x.grad

In [4]:
y = 2 * torch.dot(x, x)
y.backward()
x.grad, x.grad == 4 * x

(tensor([ 0.,  8., 16., 24.]), tensor([ True, False, False, False]))

In [5]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

#### Detaching computation

In [6]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])