Việc sử dụng mdarray trong MXNet là một dạng mở rộng của ndarray trong numpy.
ndarray trong MXNet hỗ trợ tính toán phi đồng bộ trên CPU, GPU và các kiến trúc phân tán đám mây trong khi NumPy chỉ hỗ trợ tính toán trên CPU. Bên cạnh đó, MXNet hỗ trợ tính vi phân tự động. Những tính chất này khiến ndarray của MXNet phù hợp với deep learning.

In [99]:
from mxnet import np, npx
npx.set_np()


Để bắt đầu, sử dụng hàm arange để tạp một vector hàng chứa 12 số nguyên bắt đầu từ 0 nhưng được khởi tạo mặc định dưới dạng số thực. Mỗi giá trị trong một ndarray được gọi là một phần tử của ndarray đó. Như vậy, có 12 phần tử trong ndarray x. Nếu không nói gì thêm thì một ndarray mới sẽ được lưu trong bộ nhớ chính và được tính toán trên CPU.

In [100]:
x = np.arange(12)
x
print(x.shape)
print(x.size)
print(type(x))

(12,)
12
<class 'mxnet.numpy.ndarray'>


Để thay đổi kích thước của một ndarray mà không làm thay đổi số lượng phần tử cũng như giá trị của chúng, ta có thể gọi hàm reshape. Ví dụ, ta có thể biến đổi ndarray x trong ví dụ từ vector hàng với kích thước (12,) sang một ma trận có kích thước (3, 4). 

In [101]:
x = x.reshape(3, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

Ta sẽ muốn khởi tạo ma trận với các giá trị bằng không, bằng một, bằng hằng số nào đó hoặc bằng hằng số nào khác. Ta có thể tạo một ndarray biểu diễn một tensor với tất cả phần từ bằng không và có kích thước (2, 3, 4) như sau: 

In [102]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

Tương tự với ma trận toàn số 1

In [103]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

Nếu cần sinh ra ma trận với phân phối chuẩn: Trung bình bằng 0 và độ lệch chuẩn bằng 1

In [104]:
np.random.normal(0, 1, size = (3, 4))

array([[ 1.5194443 , -1.474966  ,  1.9040879 , -0.52414197],
       [-1.5734432 ,  1.2662556 , -0.14007866,  0.8950643 ],
       [ 0.29670075, -0.60159445,  1.3111951 ,  1.2040559 ]])

Ta cũng có thể khởi tạo giá trị cụ thể cho mỗi phần tử trong ndarray mong muốn bằng cách đưa vào một mảng Python chứa các giá trị số

In [105]:
np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

array([[2., 1., 4., 3.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.]])

Ví dụ về phép toán trong MXNet

In [106]:
x = np.array([1, 2, 4, 8])
y = np.array([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # The ** operator is exponentiation

(array([ 3.,  4.,  6., 10.]),
 array([-1.,  0.,  2.,  6.]),
 array([ 2.,  4.,  8., 16.]),
 array([0.5, 1. , 2. , 4. ]),
 array([ 1.,  4., 16., 64.]))

In [107]:
np.exp(x)

array([2.7182817e+00, 7.3890562e+00, 5.4598148e+01, 2.9809580e+03])

Ta có thể nối nhiều ndarray với nhau, xếp chồng chúng lên nhau để tạp ra một ndarray lớn hơn. Ta có thể gọi nối hai ma trận theo axis = 0 theo trục x hoặc axis = 1 theo trục y.

In [108]:
x = np.arange(12).reshape(3, 4)
y = np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
np.concatenate([x, y], axis = 0), np.concatenate([x, y], axis = 1)

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]]),
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

So sánh x và y

In [109]:
x == y

array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

Tính tổng tất cả các phần tử

In [110]:
x.sum(), np.sum(x)

(array(66.), array(66.))

Trong phần trên, ta đã thực hiện các phép tính toán theo từng phần tử với hai ndarray với cùng kích thước. Trong những điều kiện nhất định thậm chí khi kích thước khác nhau ta có thể thực hiện các phép toán theo từng phần tử bnawngf cách sử dụng cơ chế lan truyền (broadcasting mechanism)
Cách hoạt động: 
1. Mở rộng một hoặc cả hai mảng bằng cách lặp lại các phần tử một cách hợp lý sao cho sau phép biến đổi thì hai mảng ndarray có cùng kích thước.
2. Thực hiện các phép toán theo từng phần tử với hai mảng mới.

In [111]:
a = np.arange(3).reshape(3, 1)
b = np.arange(2).reshape(1, 2)
a, b

(array([[0.],
        [1.],
        [2.]]),
 array([[0., 1.]]))

Vì a có kích thước 3x1 và b có kích thước 1x2 nên kích thước của chúng không khớp nếu ta muốn thực hiện phép cộng, ta sẽ biến chúng thành ma trận 3x2 bằng cách lặp các cột của ma trận a và các hàng của ma trận b trước khi cộng chúng theo từng phần tử.

In [112]:
a + b

array([[0., 1.],
       [1., 2.],
       [2., 3.]])

Chỉ số và Cắt chọn mảng (Slicing) 
Các phần tử trong một ndarray có thể dược truy cập theo chỉ số, phần tử đâì tiên có chỉ số 0 và khoảng được cắt chọn bao gồm phần tử đầu tiên nhưng không tính phần tử cuối cùng. 
Sử dụng [-1] cho phần tử cuối cùng và [1:3] chọn phần tử thứ hai và thứ ba.

In [113]:
x, x[-1], x[1 : 3]

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([ 8.,  9., 10., 11.]),
 array([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]))

Ta có thể viết các phần tử của ma trận bằng cách chỉ định các chỉ số

In [114]:
x[1, 2] = 9
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]])

Nếu ta muốn gán cùng một giá trị cho nhiều phần tử, ta cần trỏ đến tất cả các phần tử đó và gán giá trị cho chúng. 
Ví dụ [0:2, 0:2] truy cập vào hàng thứ nhất và thứ hai, trong đó : lấy các phần tử hàng có chỉ số tử 0 đến 1.

In [115]:
x[0:2, 0:2] = 12
x

array([[12., 12.,  2.,  3.],
       [12., 12.,  9.,  7.],
       [ 8.,  9., 10., 11.]])

Tiết kiệm bộ nhớ
Mỗi khi chạy một phép tính, chúng ta sẽ cấp phát bộ nhớ mới để lưu trữ kết quả của lượt chạy đó. Cụ thể, nếu viết y = x + y, ta sẽ ngừng tham chiếu điển ndarray mà y đã chỉ đến trước đó mà thay vào đó, gán y vào bộ nhớ được cấp phát mới.
Ví dụ với hàm id() của python - hàm cung cấp địa chỉ chính xác của đối tượng được tham chiếu trong bộ nhớ.
Sau khi chạy y = y + x, id(y) chỉ đến một địa chỉ khác. 

In [116]:
before = id(y)
y = y + x
id(y) == before

False

Điều này có thể không mong muốn vì hai lí do:
1. Không phải lúc nào ta cũng muốn cấp phát bộ nhớ không cần thiết. Trong học máy, ta có thể có đến hàng trăm mb tham số và cập nhật tất cả chúng nhiều lần trên mỗi giây và ta muốn thực thi các cập nhật này tại chỗ.
2. Ta có thể trỏ đến cùng tham số từ nhiều biến khác nhau. Nếu không cập nhạt tại chỗ, các bộ nhớ đã bị loại bỏ sẽ không được giải phóng, dẫn đến khả năng một số chỗ trong mã nguồn sẽ vô tình tham chiếu lại các tham số cũ.
Ta có thể thực hiện các phép tính tại chỗ với MXNet:

In [117]:
z = np.zeros_like(y)
print('id(z)', id(z))
z[:] = x + y
print("id(z)", id(z))

id(z) 2541287759128
id(z) 2541287759128


Nếu các tính toán tiếp theo không tái sử dụng giá trị của x, ta có thể viết x[:] = x + y hoặc x += y để giảm thiểu việc sử dụng bộ nhớ không cần thiết trong quá trình tính toán.

In [118]:
before = id(x)
x += y
id(x) == before

True

Chuyển đổi sang các đối tượng python khác
Chuyển đổi một MXNet ndarray sang NumPy ndarray hoặc ngược lại khá đơn giản nhưng kết quả của phép chuyển đổi này không chia sẻ bộ nhớ với đối tượng cũ. Điểm bất tiện này tuy nhỏ nhưng lại quan trọng: 
- Khi bạn thực hiện các phép tính trên CPU hoặc GPUs thì ta sẽ không muốn MXNet dừng việc tính toán để chờ xem liệu gói Numpy của python có sử dụng cùng bộ nhớ đó để làm việc khác không. 
- Ta sẽ sử dụng hàm array và asnumpy để giải quyết vấn đề này.

In [119]:
a = x.asnumpy()
b = np.array(a)
type(a), type(b)

(numpy.ndarray, mxnet.numpy.ndarray)

Để chuyển đổi một mảng ndarray chứa một phần tử sang số vô hướng Python, ta có thể gọi hàm item hoặc các hàm có sẵn trong python.

In [126]:
a = np.array([3.33])
a, a.item(), float(a), int(a)

array([[False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])