In [ ]:
from transformers import pipeline
classifier = pipeline('sentiment-analysis')
classifier([
    "Hello"
])

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Device set to use cpu


[{'label': 'POSITIVE', 'score': 0.9995185136795044}]

In [ ]:
from transformers import AutoTokenizer

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [ ]:
raw_inputs = [
    "I've been waiting for a HuggingFace course my whole life.",
    "I hate this so much!",
]
inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors="pt")
print(inputs)

{'input_ids': tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102],
        [  101,  1045,  5223,  2023,  2061,  2172,   999,   102,     0,     0,
             0,     0,     0,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])}


In [ ]:
from transformers import AutoModel

model = AutoModel.from_pretrained(checkpoint)

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Pipeline:
tokenizer -> automodel
automodel này chỉ cho ra các biểu diễn context của các input đầu vào.
- Kích thước đầu ra: (batch_size, sequence_size, hidden_size)

In [ ]:
output = model(
    **inputs
)
print(output.last_hidden_state.shape)

torch.Size([2, 16, 768])


In [ ]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(checkpoint)
outputs = model(**inputs)

In [ ]:
outputs.logits

tensor([[-1.5607,  1.6123],
        [ 4.1692, -3.3464]], grad_fn=<AddmmBackward0>)

In [ ]:
import torch
import torch.nn.functional as F

res = F.softmax(outputs.logits, dim = -1)
print(res)

tensor([[4.0195e-02, 9.5980e-01],
        [9.9946e-01, 5.4418e-04]], grad_fn=<SoftmaxBackward0>)


In [ ]:
model.config.label2id, model.config.id2label

({'NEGATIVE': 0, 'POSITIVE': 1}, {0: 'NEGATIVE', 1: 'POSITIVE'})

In [ ]:
from transformers import BertConfig, BertModel

config = BertConfig()

model = BertModel(config) # Model in randomly initialized

In [ ]:
config

BertConfig {
  "_attn_implementation_autoset": true,
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.51.3",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

In [ ]:
from transformers import BertModel

model = BertModel.from_pretrained("bert-base-cased")

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

In [ ]:
tokenizer = AutoTokenizer.from_pretrained('bert-base-cased')


tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

In [ ]:
text = ["hello!", "Bye!", "What is this?"]

input = tokenizer(text, padding = True, truncation=True, return_tensors = 'pt')

In [ ]:
input['input_ids']

tensor([[  101, 19082,   106,   102,     0,     0],
        [  101, 17774,   106,   102,     0,     0],
        [  101,  1327,  1110,  1142,   136,   102]])

In [ ]:
model(
    **input
)

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 0.5406,  0.2432,  0.4001,  ..., -0.2178,  0.6057,  0.0089],
         [ 0.6435, -0.4269,  0.8868,  ..., -0.5728,  0.2484,  0.0315],
         [ 0.8017,  0.2163,  0.9462,  ..., -0.1726,  0.6076,  0.3280],
         [ 0.8952,  0.2587, -0.0635,  ..., -0.0840,  1.1347,  0.0078],
         [ 0.1159,  0.1121,  0.6318,  ..., -0.2144,  0.4583,  0.0962],
         [ 0.0554,  0.1425,  0.6628,  ..., -0.4676,  0.2761,  0.1683]],

        [[ 0.5488,  0.2106,  0.4263,  ..., -0.0525,  0.5697, -0.0446],
         [ 0.5638, -0.1299,  0.5829,  ..., -0.4697,  0.5335,  0.1048],
         [ 0.6639,  0.2556,  0.5194,  ...,  0.0233,  0.5493,  0.0471],
         [ 0.7508,  0.4069, -0.2474,  ...,  0.4663,  1.2481, -0.2140],
         [ 0.1306,  0.0656,  0.1873,  ..., -0.1032,  0.6727,  0.0491],
         [ 0.0579,  0.1722,  0.4570,  ..., -0.2462,  0.5599,  0.1296]],

        [[ 0.3594,  0.2692,  0.4210,  ..., -0.2965,  0.5701, -0.5408],
         [

In [ ]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased") # subword tokenization
sequence = "the model likely expects the input to be unpacked or passed as keyword arguments."
tokens = tokenizer.tokenize(sequence)

print(tokens)

['the', 'model', 'likely', 'expects', 'the', 'input', 'to', 'be', 'un', '##pack', '##ed', 'or', 'passed', 'as', 'key', '##word', 'arguments', '.']


In [ ]:
ids = tokenizer.convert_tokens_to_ids(tokens)

print(ids)

[1103, 2235, 2620, 27402, 1103, 7758, 1106, 1129, 8362, 27569, 1174, 1137, 2085, 1112, 2501, 12565, 9989, 119]


In [ ]:
decoded_sequence = tokenizer.decode(ids) # return string
decoded_sequence = tokenizer.convert_ids_to_tokens(ids) # return tokens

print(decoded_sequence)

['the', 'model', 'likely', 'expects', 'the', 'input', 'to', 'be', 'un', '##pack', '##ed', 'or', 'passed', 'as', 'key', '##word', 'arguments', '.']


In [ ]:
# Handle multiple sentence?
# Handle different length sequence?
# Sequence too long


In [10]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

In [16]:
sequence = "I've been waiting for a HuggingFace course my whole life."

tokens = tokenizer.tokenize(sequence)
ids = tokenizer.convert_tokens_to_ids(tokens)

input = torch.tensor(ids).reshape(1, -1)
output = model(input)

logits = output.logits.detach().numpy()

print('logits: ', logits)

logits:  [[-2.7276213  2.878938 ]]


In [17]:
# với trường hợp các sentence không cùng độ dài, sử dụng padding để cùng độ dài.
# Thêm attention mask để mô hình biết sẽ không tính toán attention từ những token padding
batched_ids = [
    [200, 200, 200],
    [200, 200, tokenizer.pad_token_id],
]

attention_mask = [
    [1, 1, 1],
    [1, 1, 0],
]

outputs = model(torch.tensor(batched_ids), attention_mask=torch.tensor(attention_mask))
print(outputs.logits)

tensor([[ 1.5694, -1.3895],
        [ 0.5803, -0.4125]], grad_fn=<AddmmBackward0>)


In [18]:
sequence1_ids = [[200, 200, 200]]
sequence2_ids = [[200, 200]]

print(model(torch.tensor(sequence1_ids)).logits)
print(model(torch.tensor(sequence2_ids)).logits)

tensor([[ 1.5694, -1.3895]], grad_fn=<AddmmBackward0>)
tensor([[ 0.5803, -0.4125]], grad_fn=<AddmmBackward0>)


In [ ]:
# với trường hợp độ dài sequence quá lớn
# sử dụng mô hình khác hỗ trợ sequence_size dài hơn
# truncate sequence cho vừa

In [6]:
!pip install -U datasets

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.5/491.5 kB 9.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.6/193.6 kB 16.0 MB/s eta 0:00:00
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.2
    Uninstalling fsspec-2025.3.2:
      Successfully uninstalled fsspec-2025.3.2
  Attempting uninstall: datasets
    Found existing installation: datasets 2.14.4
    Uninstalling datasets-2.14.4:
      Successfully uninstalled datasets-2.14.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch 2.6.0+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.5.3.2 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-cupti-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-cupti-cu12 

In [1]:
from datasets import load_dataset

raw = load_dataset("SetFit/mrpc")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


README.md:   0%|          | 0.00/316 [00:00<?, ?B/s]

Repo card metadata block was not found. Setting CardData to empty.


train.jsonl:   0%|          | 0.00/1.14M [00:00<?, ?B/s]

validation.jsonl:   0%|          | 0.00/127k [00:00<?, ?B/s]

test.jsonl:   0%|          | 0.00/533k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/3668 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/408 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1725 [00:00<?, ? examples/s]

In [2]:
print(raw)

DatasetDict({
    train: Dataset({
        features: ['text1', 'text2', 'label', 'idx', 'label_text'],
        num_rows: 3668
    })
    validation: Dataset({
        features: ['text1', 'text2', 'label', 'idx', 'label_text'],
        num_rows: 408
    })
    test: Dataset({
        features: ['text1', 'text2', 'label', 'idx', 'label_text'],
        num_rows: 1725
    })
})


In [9]:
train_set = raw['train']

def print_row(idx):
  print(train_set[idx]['text1'])
  print(train_set[idx]['text2'])
  print(train_set[idx]['label'])
  print(train_set[idx]['label_text'])

print_row(1)

Yucaipa owned Dominick 's before selling the chain to Safeway in 1998 for $ 2.5 billion .
Yucaipa bought Dominick 's in 1995 for $ 693 million and sold it to Safeway for $ 1.8 billion in 1998 .
0
not equivalent


In [ ]:
train_set['text1']

In [11]:
print(train_set.features)

{'text1': Value(dtype='string', id=None), 'text2': Value(dtype='string', id=None), 'label': Value(dtype='int64', id=None), 'idx': Value(dtype='int64', id=None), 'label_text': Value(dtype='string', id=None)}


In [15]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('bert-base-cased')
tokenized_text1 = tokenizer(train_set['text1'])
tokenized_text2 = tokenizer(train_set['text2'])

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

In [22]:
# test tokenizer with a pair of sentences
inputs = tokenizer("Sentence 1", "Sentence 2")
print(inputs)


print(tokenizer.convert_ids_to_tokens(inputs['input_ids']))
# Note: token_type_ids tell model the position of a sentence

{'input_ids': [101, 14895, 5208, 2093, 122, 102, 14895, 5208, 2093, 123, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
['[CLS]', 'Sen', '##ten', '##ce', '1', '[SEP]', 'Sen', '##ten', '##ce', '2', '[SEP]']


In [20]:
inputs = tokenizer(train_set['text1'], train_set['text2'], padding = True, return_tensors='pt', truncation=True)
inputs['input_ids'].shape

torch.Size([3668, 111])

vấn đề:
- Tốn ram để lưu trữ cả ma trận input
- dictionary trả về phức tạp
-> Sử dụng Dataset.map() method, những phần nào của dataset cần dùng thì mới đưa vào trong ram, còn lại là lưu ở ổ đĩa.
- Note: Không sử dụng padding trong hàm tokenizer_function. Mà sử dụng padding trong khi tạo batch. Việc này sẽ nhanh hơn padding trong cả tập dữ liệu.

In [29]:
def tokenizer_function(example):
  return tokenizer(example['text1'], example['text2'], truncation= True)

tokenizer_datasets = raw.map(tokenizer_function, batched=True)

Map:   0%|          | 0/3668 [00:00<?, ? examples/s]

Map:   0%|          | 0/408 [00:00<?, ? examples/s]

Map:   0%|          | 0/1725 [00:00<?, ? examples/s]

In [31]:
tokenizer_datasets

DatasetDict({
    train: Dataset({
        features: ['text1', 'text2', 'label', 'idx', 'label_text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 3668
    })
    validation: Dataset({
        features: ['text1', 'text2', 'label', 'idx', 'label_text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 408
    })
    test: Dataset({
        features: ['text1', 'text2', 'label', 'idx', 'label_text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 1725
    })
})

In [33]:
from transformers import DataCollatorWithPadding

data_collator = DataCollatorWithPadding(tokenizer = tokenizer)

In [69]:
samples = tokenizer_datasets['train'][:10] # batch_size = 10
samples = {k:v for k, v in samples.items() if k not in ['idx', 'label_text', 'text1', 'text2']}
[len(x) for x in samples['input_ids']]
list(samples.keys())

['label', 'input_ids', 'token_type_ids', 'attention_mask']

In [47]:
batch = data_collator(samples)
{k:v.shape for k, v in batch.items()}

{'input_ids': torch.Size([10, 69]),
 'token_type_ids': torch.Size([10, 69]),
 'attention_mask': torch.Size([10, 69]),
 'labels': torch.Size([10])}

In [91]:
from random import randint
def get_batch(tokenized_datasets, data_collator : DataCollatorWithPadding, batch_size, dataset_type = 'train',
              removed_keys = ['idx', 'label_text', 'text1', 'text2']):
  samples = tokenized_datasets[dataset_type]
  print(samples.num_rows)
  idx = randint(0, samples.num_rows - batch_size)
  samples = samples[idx:idx + batch_size]
  samples = {k:v for k, v in samples.items() if k not in removed_keys}
  batch = data_collator(samples)
  return batch

In [92]:
batch = get_batch(tokenizer_datasets, data_collator, 20)
{k:v.shape for k, v in batch.items()}

3668


{'input_ids': torch.Size([20, 72]),
 'token_type_ids': torch.Size([20, 72]),
 'attention_mask': torch.Size([20, 72]),
 'labels': torch.Size([20])}

In [97]:
raw_dataset2 = load_dataset('nyu-mll/glue', 'sst2')

raw_dataset2

train-00000-of-00001.parquet:   0%|          | 0.00/3.11M [00:00<?, ?B/s]

validation-00000-of-00001.parquet:   0%|          | 0.00/72.8k [00:00<?, ?B/s]

test-00000-of-00001.parquet:   0%|          | 0.00/148k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/67349 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/872 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1821 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['sentence', 'label', 'idx'],
        num_rows: 67349
    })
    validation: Dataset({
        features: ['sentence', 'label', 'idx'],
        num_rows: 872
    })
    test: Dataset({
        features: ['sentence', 'label', 'idx'],
        num_rows: 1821
    })
})

In [98]:
train_dataset = raw_dataset2['train']
train_dataset[:3]

{'sentence': ['hide new secretions from the parental units ',
  'contains no wit , only labored gags ',
  'that loves its characters and communicates something rather beautiful about human nature '],
 'label': [0, 0, 1],
 'idx': [0, 1, 2]}

In [105]:
tokenizer = AutoTokenizer.from_pretrained('bert-base-cased')
data_collator = DataCollatorWithPadding(tokenizer)
def tokenizer_function(example):
  return tokenizer(example['sentence'], truncation= True)
tokenized_dataset2 = raw_dataset2.map(tokenizer_function, batched=True)

Map:   0%|          | 0/872 [00:00<?, ? examples/s]

In [ ]:
tokenized_dataset2['train'][:10]

In [112]:
get_batch(
    tokenized_dataset2, data_collator, 64, removed_keys = ['idx', 'sentence']
)

67349


{'input_ids': tensor([[  101,  2771, 16038,  ...,     0,     0,     0],
        [  101,  1132,  7226,  ...,     0,     0,     0],
        [  101,  1122,   112,  ...,     0,     0,     0],
        ...,
        [  101,  2887,   119,  ...,     0,     0,     0],
        [  101, 14257,   102,  ...,     0,     0,     0],
        [  101,   170,   188,  ...,     0,     0,     0]]), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
        0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 