In [63]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [64]:
# Introduction to Tensors

# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [65]:
scalar.ndim

0

In [66]:
scalar.item()

7

In [67]:
# vector
vector = torch.tensor([7, 7])
vector, vector.ndim, vector.shape

(tensor([7, 7]), 1, torch.Size([2]))

In [68]:
# matrix
A = torch.tensor([[4, 5, 3], 
                  [5, 6, 7]])
A

tensor([[4, 5, 3],
        [5, 6, 7]])

In [69]:
A.shape, A.ndim

(torch.Size([2, 3]), 2)

In [70]:
A[0][0]

tensor(4)

In [71]:
# Random tensors
A = torch.rand(size = (3, 4))
A

tensor([[0.0349, 0.5641, 0.7292, 0.8802],
        [0.5982, 0.8884, 0.1399, 0.9709],
        [0.2446, 0.9381, 0.0086, 0.8521]])

In [72]:
A.ndim, A.shape

(2, torch.Size([3, 4]))

In [73]:
image_tensor = torch.rand(size = (224, 224, 3))
# height, width, color channel
image_tensor.shape, image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [74]:
A = torch.zeros(size = (3, 3))
A

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [75]:
A = torch.ones(size = (3, 3))
A

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [76]:
B = torch.zeros_like(A)
B

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [77]:
B.dtype

torch.float32

In [78]:
A = torch.arange(12, dtype = torch.float16).reshape(3, 4)
# A.dtype = torch.float64
A = torch.tensor(A, dtype=torch.float64)
A

C:\Users\Duc Anh\AppData\Local\Temp\ipykernel_16716\3349346768.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  A = torch.tensor(A, dtype=torch.float64)


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

In [79]:
A = torch.randn(size = (3, 4), 
                dtype = torch.float64,
                device = 'cuda',
                requires_grad=True)
A

tensor([[ 0.1286, -0.2301, -0.1967, -1.3743],
        [-1.0185,  0.4737, -0.4393,  0.6162],
        [-0.3117,  1.7813,  1.4026,  0.7040]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)

In [80]:
A = A.type(dtype = torch.float16)
A.requires_grad_ = False
A

tensor([[ 0.1287, -0.2301, -0.1967, -1.3740],
        [-1.0186,  0.4736, -0.4392,  0.6162],
        [-0.3118,  1.7812,  1.4023,  0.7041]], device='cuda:0',
       dtype=torch.float16, grad_fn=<ToCopyBackward0>)

In [81]:
tensor = torch.arange(10).reshape(2, 5)
tensor, tensor + 10, tensor * 10, tensor / 10, torch.exp(tensor)

(tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]),
 tensor([[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]),
 tensor([[ 0, 10, 20, 30, 40],
         [50, 60, 70, 80, 90]]),
 tensor([[0.0000, 0.1000, 0.2000, 0.3000, 0.4000],
         [0.5000, 0.6000, 0.7000, 0.8000, 0.9000]]),
 tensor([[1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
         [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03]]))

In [82]:
tensor2 = tensor.T
tensor2.shape, tensor.shape

(torch.Size([5, 2]), torch.Size([2, 5]))

In [83]:
torch.matmul(tensor2, tensor).shape

torch.Size([5, 5])

In [84]:
x = torch.ones(size = (2, 2))
y = torch.ones_like(x) * 4

# x * y: Nhân hai phần tử tương ứng vị trí
# torch.matmul: Nhân hai ma trận
x * y, torch.matmul(x, y)

(tensor([[4., 4.],
         [4., 4.]]),
 tensor([[8., 8.],
         [8., 8.]]))

#### Reshaping, stacking, squeezing and unsqueezing
- torch.reshape(input, shape): Reshape input to shape.
- Tensor.view(shape): Return a view of the original tensor in different shape but shape the same data as the original tensor.
- torch.stack(tensors, dim = 0): concatenates a sequence of tensors along a new dimension (dim), all tensors must be the same size.
- torch.squeeze(input): Squeezes input to remove all the dimensions with value 1
- torch.unsqueeze(input, dim): Return input with a dimension value of 1 added at dim.
- torch.permute(input, dims): Returns a view of the original input with its dimensions permuted to dims.

In [85]:
x = torch.arange(12).reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [86]:
y = x.view(4, 3)
print(y) # Khi x hay y thay đổi thì cái còn lại cũng thay đổi
y -= 10
print("y = ", y)
print("x = ", x)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
y =  tensor([[-10,  -9,  -8],
        [ -7,  -6,  -5],
        [ -4,  -3,  -2],
        [ -1,   0,   1]])
x =  tensor([[-10,  -9,  -8,  -7],
        [ -6,  -5,  -4,  -3],
        [ -2,  -1,   0,   1]])


In [87]:
x = torch.arange(12).reshape(3, 4)
y = torch.arange(12).reshape(3, 4) * 3
z = torch.stack((x, y), dim = 0)
print(z, z.shape)

z = torch.stack((x, y), dim = 1)
print(z, z.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[ 0,  3,  6,  9],
         [12, 15, 18, 21],
         [24, 27, 30, 33]]]) torch.Size([2, 3, 4])
tensor([[[ 0,  1,  2,  3],
         [ 0,  3,  6,  9]],

        [[ 4,  5,  6,  7],
         [12, 15, 18, 21]],

        [[ 8,  9, 10, 11],
         [24, 27, 30, 33]]]) torch.Size([3, 2, 4])


In [88]:
x = x.reshape(1, 1, 3, 4)
x.shape

torch.Size([1, 1, 3, 4])

In [89]:
x = x.squeeze()
x.shape

torch.Size([3, 4])

In [90]:
x = x.unsqueeze(dim = 1)
x.shape

torch.Size([3, 1, 4])

In [91]:
x = x.reshape(3, 4)
# Di chuyển chiều, dim 3 lên vị trí 1, dim 4 về vị trí 0
y = torch.permute(x, dims = (1, 0))
y.shape

torch.Size([4, 3])

#### Pytorch and numpy

In [94]:
import numpy as np

array = np.arange(12).reshape(1, 12)
tensor = torch.from_numpy(array)

array, tensor, tensor.type(dtype = torch.float32)

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]),
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]], dtype=torch.int32),
 tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]]))

In [97]:
RANDOM_SEED = 42
torch.manual_seed(seed = RANDOM_SEED)
tensor1 = torch.rand(size = (3, 3))

torch.random.manual_seed(seed = RANDOM_SEED)
tensor2 = torch.rand(size = (3, 3))

tensor1 == tensor2

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

#### Running tensors on GPUs to make faster computation

In [98]:
torch.cuda.is_available()

True

In [99]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [100]:
# Count number of devices
torch.cuda.device_count()

1

In [102]:
# Create tensor default on CPU
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)
tensor_gpu = tensor.to(device = device)
print(tensor_gpu, tensor_gpu.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cuda:0


In [105]:
# Convert tensor from GPU to numpy
array = tensor_gpu.cpu().numpy()
array

array([1, 2, 3], dtype=int64)