In [46]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [47]:
# Introduction to Tensors

# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [48]:
scalar.ndim

0

In [49]:
scalar.item()

7

In [50]:
# vector
vector = torch.tensor([7, 7])
vector, vector.ndim, vector.shape

(tensor([7, 7]), 1, torch.Size([2]))

In [51]:
# matrix
A = torch.tensor([[4, 5, 3], 
                  [5, 6, 7]])
A

tensor([[4, 5, 3],
        [5, 6, 7]])

In [52]:
A.shape, A.ndim

(torch.Size([2, 3]), 2)

In [53]:
A[0][0]

tensor(4)

In [54]:
# Random tensors
A = torch.rand(size = (3, 4))
A

tensor([[0.4858, 0.7042, 0.5324, 0.9272],
        [0.7039, 0.7867, 0.1344, 0.0564],
        [0.4240, 0.9132, 0.6257, 0.6800]])

In [55]:
A.ndim, A.shape

(2, torch.Size([3, 4]))

In [56]:
image_tensor = torch.rand(size = (224, 224, 3))
# height, width, color channel
image_tensor.shape, image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [57]:
A = torch.zeros(size = (3, 3))
A

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [58]:
A = torch.ones(size = (3, 3))
A

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [59]:
B = torch.zeros_like(A)
B

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [60]:
B.dtype

torch.float32

In [61]:
A = torch.arange(12, dtype = torch.float16).reshape(3, 4)
# A.dtype = torch.float64
A = torch.tensor(A, dtype=torch.float64)
A

C:\Users\Duc Anh\AppData\Local\Temp\ipykernel_18560\3349346768.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  A = torch.tensor(A, dtype=torch.float64)


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

In [62]:
A = torch.randn(size = (3, 4), 
                dtype = torch.float64,
                device = 'cuda',
                requires_grad=True)
A

tensor([[-0.4370,  0.5952, -1.0585,  0.5019],
        [-0.2491, -1.1296,  2.1017,  1.2904],
        [-0.7764, -0.8337,  0.2176, -0.1938]], device='cuda:0',
       dtype=torch.float64, requires_grad=True)

In [63]:
A = A.type(dtype = torch.float16)
A.requires_grad_ = False
A

tensor([[-0.4370,  0.5952, -1.0586,  0.5020],
        [-0.2491, -1.1299,  2.1016,  1.2900],
        [-0.7764, -0.8335,  0.2175, -0.1937]], device='cuda:0',
       dtype=torch.float16, grad_fn=<ToCopyBackward0>)